### ISSUE TITLE
Comentários

### ISSUE THREAD

**Issue by pmizukami** [pensandoodireito/participacao-tema#25]
Após tentar inserir comentário em uma pauta (http://participacao.mj.gov.br/marcocivil/pauta/marco-civil-sera-para-perseguir-e-processar-quem-falar-mal-do-governo-na-internet/), a plataforma retornou a mensagem: "Você está enviando comentários rápido demais. Calma aí.". Foi o primeiro comentário que tentei enviar com o perfil.

Repeti o experimento após fazer logout, recarregar a página e apagar os cookies, sempre com o mesmo resultado. Navegadores: Chrome e Firefox.

**Comment by prenass** [comment]
![captura de tela 2015-01-29 as 23 21 48](https://cloud.githubusercontent.com/assets/6624198/5969681/d930c378-a80d-11e4-9807-c4d335c0db36.png)
Tive o mesmo problema. Recebi exatamente a mesma mensagem já no meu primeiro comentário, no caso, feito em um <a href="http://participacao.mj.gov.br/marcocivil/pauta/fim-do-corte-da-internet">post criado por outro usuário</a>.
Tentei usando o Firefox 35.0 em um Mac.

**Comment by prenass** [comment]
Dica: apertar para voltar a página permitiu copiar e colar o texto do comentário em outro lugar para quando ele puder ser publicado. Repito, estou usando o Firefox 35.0 em um Mac.

**Comment by marcoamarelo** [comment]
De que rede você está comentando @prenass? É uma rede privada ou alguma rede maior?

**Comment by marcoamarelo** [comment]
Bug resolvido retirando o filtro de controle do comment_flood
