### ISSUE TITLE
Painel - acompanhamento da própria participação

### ISSUE THREAD

**Issue by prenass** [pensandoodireito/participacao-tema#26]
Seria possível incluir no painel uma forma de visualizar rapidamente todos os tópicos em que já comentei, além dos tópicos que eu mesmo criei?
Há já algum outro caminho para essa funcionalidade?

**Comment by marcoamarelo** [comment]
É uma funcionalidade bem interessante @prenass, mas teríamos que desenvolvê-la. Vou colocar como prioridade depois de melhorarmos algumas coisas de interação que estão pendentes.

**Comment by diraol** [comment]
Issue transferida para o repositório "pensandoodireito-sitebase"
