### ISSUE TITLE
Tageamento colaborativo para apoio a sistematização

### ISSUE THREAD

**Issue by marcoamarelo** [pensandoodireito/participacao-tema#29]
Seria legal termos um sistema em que as pessoas poderiam sugerir palavras-chave pra comentários e pautas que seriam sugestões individuais. Com o cruzamento das sugestões, poderíamos encontrar palavras-chave mais relevantes.

**Comment by diraol** [comment]
Issue transferida para o repositório "pensandoodireito-sitebase"

**Comment by marcoamarelo** [comment]
participacao-sitebase
