### ISSUE TITLE
Busca para facilitar a localização de pautas

### ISSUE THREAD

**Issue by eduspano** [pensandoodireito/participacao-tema#30]
Conforme proposta postada na própria plataforma (http://participacao.mj.gov.br/marcocivil/pauta/proposta-antes-de-criar-uma-nova-pauta-verifique-se-ja-nao-ha-alguma-que-o-contemple/), é importante que os participantes do debate público verifiquem se já existe uma pauta sobre o assunto que queiram contribuir. Assim, teremos debates mais sistematizados. Por isso, implementar um mecanismo de busca que possibilite que os participantes encontrem mais facilmente as pautas contribuiria para o debate.

**Comment by marcoamarelo** [comment]
Recurso implementado com o commit 12a5cd8839c6aa27ec99beedf84448a1490e6800
