### ISSUE TITLE
Dead End na mudança de senha

### ISSUE THREAD

**Issue by tiaeaugusto** [pensandoodireito/participacao-tema#31]
Como já sabemos, a senha inicialmente atribuída sem participação do usuário vem em formato totalmente imemorizável. Para fazer sua modificação, apenas quem já tem alguma intimidade com o Wordpress vai encontrar o link no canto direito superior. Mas mesmo que o faça, depois de alterada a senha não há caminho de volta para a página principal.

**Comment by diraol** [comment]
Issue transferida para o repositório "pensandoodireito-sitebase"
