### ISSUE TITLE
Menu principal - proponha um debate

### ISSUE THREAD

**Issue by marilucchesi** [pensandoodireito/participacao-tema#46]
incluir "proponha um debate"  no menu principal

**Comment by marilucchesi** [comment]
@thsl adiantei aqui pra vc 
    <div id="navegacao-destaque">
        <div class="container">
            <ul class="navegacao-destaque-list">
                <li class="navegacao-destaque-item">
                    <div class="navegacao-destaque-content">
                        <h5><a href="#">Conheça o projeto</a></h5>
                        <p><a href="#">Criado para promover a democratização do processo de elaboração legislativa</a>
                        </p>
                    </div>
                </li>
                <li class="navegacao-destaque-item">
                    <div class="navegacao-destaque-content">
                        <h5><a href="#">Publicações</a></h5>
                        <p><a href="#">Conheça as publicações da Série Pensando o Direito</a>
                        </p>
                    </div>
                </li>
                <li class="navegacao-destaque-item">
                    <div class="navegacao-destaque-content">
                        <h5><a href="#">Debates</a></h5>
                        <p><a href="#">Veja os debates abertos. Sua participação é muito importante</a>
                        </p>
                    </div>
                </li>
                 <li class="navegacao-destaque-item">
                    <div class="navegacao-destaque-content">
                        <h5><a href="#">Proponha um debate</a></h5>
                        <p><a href="#">Gostaria de ver algum tema ser debatido? Faça aqui sua proposta</a>
                        </p>
                    </div>
                </li>
            </ul>
        </div>
    </div>

**Comment by marilucchesi** [comment]
@thsl te enviei o trecho do html por email. aproveitei e fiz pro "proponha um debate" qnd fechar essa issue pode fechar a https://github.com/pensandoodireito/participacao-tema/issues/47 tbm.

**Comment by thsl** [comment]
Concluído! Também corrigi algumas coisas no HTML da home!
