### ISSUE TITLE
Banner inicial página do Marco Civil da Internet

### ISSUE THREAD

**Issue by mariaeduardacintra** [pensandoodireito/participacao-tema#5]
Prezados, 
Notei que o texto utilizado no Banner inicial aponta o Marco Civil  como sendo a primeira lei construída de forma colaborativa entre Governo e sociedade utilizando a internet como plataforma de debate.
Vale notar que o apesar de o Marco Civil ter inovado ao ampliar o debate de maneira nunca antes feita, ele não foi a primeira lei a se valer da internet como plataforma de debate. Podemos citar outras consultas públicas que ocorreram dessa maneira, como: CPC, Classificação Indicativa, Consultas da Anatel para regulamentos específicos entre outras. 
Por essa razão, sugiro a alteração dessa frase inicial do Banner para:
O Marco Civil da Internet, Lei 12.965/14, que estabelece princípios, garantias, direitos e deveres dos usuários da Internet no Brasil, é uma lei construída de forma colaborativa entre Governo e sociedade utilizando a internet como plataforma de debate.

**Comment by marcoamarelo** [comment]
Texto alterado.
