### ISSUE TITLE
Ícone "Outros Temas e Considerações"

### ISSUE THREAD

**Issue by paulocesarferreira** [pensandoodireito/participacao-tema#8]
Quando abrimos a página que trata de "Outros temas e Considerações", a forma que o texto se encontra deixa as informações confusas. A parte do contexto está junto do dispositivo do Marco Civil citado, diferente da organização do ícone anterior ("Neutralidade"), que está melhor separado. Além disso, o texto termina faltando completar a frase ("A regulamentação também poderá").

**Comment by marcoamarelo** [comment]
Aqui alteraremos na hora de mexer nos conteúdos da plataforma.

**Comment by diraol** [comment]
Issue transferida para o repositório "pensandoodireito-sitebase"

**Comment by marcoamarelo** [comment]
participacao-sitebase
